/**
 * A minimal PNG *decoder* for the test suite.
 *
 * `src/core/png.ts` writes PNGs (CNV-06) but never reads one, because nothing
 * in the product needs to: pdf.js decodes images at run time. A test that has
 * to assert on real photographic pixels does need to, and pulling in an image
 * library for it would put a dependency in the tree for the sake of one
 * fixture.
 *
 * Handles what the fixture corpus actually contains — 8-bit non-interlaced
 * truecolour, with or without alpha — and all five scanline filters, so the
 * fixture can be regenerated by any encoder rather than only by one told to
 * disable filtering.
 */
import { unzlibSync } from 'fflate';

export interface DecodedPng {
  rgba: Uint8ClampedArray;
  width: number;
  height: number;
}

export function decodePng(bytes: Uint8Array): DecodedPng {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  let pos = 8; // Skip the 8-byte signature.
  let width = 0;
  let height = 0;
  let channels = 0;
  const idat: Uint8Array[] = [];

  while (pos + 8 <= bytes.length) {
    const length = view.getUint32(pos);
    const type = String.fromCharCode(...bytes.subarray(pos + 4, pos + 8));
    const data = bytes.subarray(pos + 8, pos + 8 + length);
    if (type === 'IHDR') {
      width = view.getUint32(pos + 8);
      height = view.getUint32(pos + 12);
      const bitDepth = data[8];
      const colorType = data[9];
      const interlace = data[12];
      if (bitDepth !== 8) throw new Error(`decodePng: only 8-bit is supported, got ${bitDepth}`);
      if (interlace !== 0) throw new Error('decodePng: interlaced PNGs are not supported');
      if (colorType === 2) channels = 3;
      else if (colorType === 6) channels = 4;
      else throw new Error(`decodePng: unsupported colour type ${colorType}`);
    } else if (type === 'IDAT') {
      idat.push(data);
    } else if (type === 'IEND') {
      break;
    }
    pos += 12 + length; // length + type + data + CRC
  }
  if (width === 0 || height === 0) throw new Error('decodePng: no IHDR found');

  const total = idat.reduce((n, chunk) => n + chunk.length, 0);
  const merged = new Uint8Array(total);
  let offset = 0;
  for (const chunk of idat) {
    merged.set(chunk, offset);
    offset += chunk.length;
  }

  const raw = unzlibSync(merged);
  const stride = width * channels;
  const out = new Uint8Array(height * stride);

  for (let y = 0; y < height; y++) {
    const filter = raw[y * (stride + 1)];
    const from = y * (stride + 1) + 1;
    const rowStart = y * stride;
    const priorStart = rowStart - stride;
    for (let i = 0; i < stride; i++) {
      const x = raw[from + i];
      const a = i >= channels ? out[rowStart + i - channels] : 0;
      const b = y > 0 ? out[priorStart + i] : 0;
      const c = y > 0 && i >= channels ? out[priorStart + i - channels] : 0;
      let value: number;
      switch (filter) {
        case 0:
          value = x;
          break;
        case 1:
          value = x + a;
          break;
        case 2:
          value = x + b;
          break;
        case 3:
          value = x + ((a + b) >> 1);
          break;
        case 4:
          value = x + paeth(a, b, c);
          break;
        default:
          throw new Error(`decodePng: unknown scanline filter ${filter}`);
      }
      out[rowStart + i] = value & 0xff;
    }
  }

  const rgba = new Uint8ClampedArray(width * height * 4);
  for (let p = 0; p < width * height; p++) {
    rgba[p * 4] = out[p * channels];
    rgba[p * 4 + 1] = out[p * channels + 1];
    rgba[p * 4 + 2] = out[p * channels + 2];
    rgba[p * 4 + 3] = channels === 4 ? out[p * channels + 3] : 255;
  }
  return { rgba, width, height };
}

function paeth(a: number, b: number, c: number): number {
  const p = a + b - c;
  const pa = Math.abs(p - a);
  const pb = Math.abs(p - b);
  const pc = Math.abs(p - c);
  if (pa <= pb && pa <= pc) return a;
  return pb <= pc ? b : c;
}
